### ISSUE TITLE
Allow selection of regions

### ISSUE THREAD

**Issue by kiler129** [marcomontalbano/speedtest-for-digitalocean#1]
It will be nice to get a checkbox next to `NORTH AMERICA`, `EUROPE` etc which selects/deselects all servers in a given region.

**Comment by marcomontalbano** [comment]
Thank you for the idea, this is very cool! I'll implement this and let you know.

**Comment by marcomontalbano** [comment]
I just release it in production. I added 3 checkboxes next to the region names as you suggested.
