### ISSUE TITLE
Allow selections of type of test

### ISSUE THREAD

**Issue by kiler129** [marcomontalbano/speedtest-for-digitalocean#2]
It will be nice if the web app had an option to select just ping/just download/just upload tests instead of running all of them (which takes a lot of time ;)).

**Comment by marcomontalbano** [comment]
Unfortunately, this is not possible. I'm using the same service that DigitalOcean is using for speed tests (e.g. http://speedtest-nyc1.digitalocean.com/) and this starts from `ping`, then test the `download` and finally the `upload`.
I added a "Check only the fastest 4" feature to speed up the execution time and fully-check only relevant servers.
